Main Headers
===========
:Author:    Ihsan Beyhan
:Email:     ihsan.beyhan@verapi.com
:Date:      17/01/2019
:Revision:  17/01/2019

=== Organization Membership Invitation, Request, Approval

Organization Admin manages the members of his own Organization.


Membership to an organization is requested on both Directions.

An Organization Admin can send an invitation to a user on Abyss Playform or outside of the Patform to be a member of own organization.

A user also can send a request to be a member of that organization.


---
{sp} +

==== Approval Request by an Organization Owner

An organization Administer can add a platform user to his own organization.

* Organization owner selects a user from a directory and sends a invitation request.

* Platform user receives a notification shown on notificatiopn icon.

* By clicking notification icon, system directs Platform User to task screen.

* Platform User clicks pending approvals on task screen and click accept button (or can reject this invitation).

* System sends a notification to Organization Administer to inform about approvel or rejection.
 


*****
If you want to resend invitation mail to the user, go to waiting approvals on task screen and click resend activation mail button.

*****

==== Approval Request by a Platform User


A platform User can send a request to an organization to be a member of this organization by following steps:

* Platform User finds and selects an organization and sends an intivation to the Administer of organization.

* Organization Administer receives a notification about the request and clicks notification icon.

* By clicking notification icon, system directs Organization Administer to task scren.

* Organization Administer clicks pending approvals on task screen and click accept button (or can reject this invitation).

* System sends a notification to Platform User to inform about approval or rejection.

