Main Header
===========
:Author:    Ihsan Beyhan
:Email:     ihsan.beyhan@verapi.com
:Date:      17/01/2019
:Revision:  01/02/2019



== Users

You must define an Organization Administer Role to manage users in Organizations.

****
Ogranization Administer have access to 

* Manage User
.. Invite User
.. Creat User
.. Edit User
.. Enable/disable User
.. Delete User
... Delete User from Organization
... Delete User from Group in Organization
* Manage User Roles
* Manage User Permissions

****

[NOTE]
When you delete a user from your Organizations, All the user's roles and permissions are romeved.
When deleting from a groups, all user's roles and permissions for only selected grups are romeved.




An Organization Administer can only manage users in his own Organizations.


[NOTE]
User name must be unique.

Organization Administer can add User in 2 ways:
* Cy creating User directly
* By inviting to Organization

If Organization Administer choose to add User direcly without invitation from inside Abyss Platform, just fills the required user informations and select a role for user and complete adding.

If you as an Organization Administer choose the option to add a user by intivation, you also need to select a role to assign to User. 
Invited User sees the invitation mail in his mailbox. If clicks the link, system directs User to signup page of Abyss. 
