Main Header
===========
:Author:    Ihsan Beyhan
:Email:     ihsan.beyhan@verapi.com
:Date:      17/01/2019
:Revision:  14/02/2019


== Organization

Organization is the root level of Abyss Platform.

When you signed up to Abyss Platform, sign up screen directs you to create an organization by typing organization name before login to Abyss Platform.

You can also create sub organizations.

You are assined as Organization Administer role automatically when you signed up.

As an Organization Administer, you can view, configure and manage APIs, APPs, users, groups, permissions, roles, events etc in the Organization.



Organization name and icon are displayed on the top of the left side of the page.

You can navigate between your organizations by clicking organization icon.

On Organization screen under Admin menu, you can manage your organizations such as add, edit, remove child organizations, add, remove, enable/disable users.


Multiple users can be a member of an Organization. A User can also be a memeber of different organizations.

Users share resources, applications, API's and environments according to assigned roles and permissions in the organiation.



NOTE: In trial mode you have one default organization and you dont have access edit it or create new organizations.
