Main Header
===========
:Author:    Ihsan Beyhan
:Email:     ihsan.beyhan@verapi.com
:Date:      17/01/2019
:Revision:  21/01/2019


=== Create an Abyss Platform Account

Go to the signup page.

A form appears, where you can provide your contact information and create a user name and password.

Enter the following:

Username - Must be at least 3 characters and contain only the following: alphanumeric characters, dashes, or underscores.

Password - Must be at least 6 characters in length and contain only the following: upper and lower case characters, numbers, and non-alphanumeric symbols.

Company - Can be any name unless you were invited to join an existing organization, in which case the company name is already set.

Anypoint Platform creates a new organization using the company name you entered and makes you the administrator of that organization. An Anypoint Platform account can be associated with only one organization.

Agree to the terms of service.

=== Accepting an Invitation to an Existing Organization
If someone else has already created an Anypoint Platform organization that you want to join, ask them for an invitation to that organization. When an administrator invites you to the organization, you receive an email with a link to accept the invitation.

Click the link you received in the Anypoint invitation email.
You must use the email address to which the invitation email was sent to sign up for an account with that organization. The Anypoint Platform signup screen appears.

Enter the following information in the form:

Full name - First and last name.

Email address - If your email address is associated with more than one Anypoint Platform account, after clicking the link in the invitation choose one of the following:

Using an Existing Account

Creating a New Account Within an Existing Organization

Phone number - Phone number with area code.

Username - You can use the same email address for multiple Anypoint Platform accounts, but each account needs a unique username. This enables you to manage all of your Anypoint Platform accounts under a single email address.
Must be at least 3 characters and contain only the following: alphanumeric characters, dashes, or underscores.

Password - Must be at least 6 characters in length and contain only the following: upper and lower case characters, numbers, and non-alphanumeric symbols.

Agree to the terms of service and privacy policy, then click Accept and create account in 

=== Using an Existing Account
You can use an existing account to join an existing organization once you receive an invitation. For example, assume that you are invited to join the MuleSoft Organization, and that you have three different accounts:

Member: An account not associated with any organization.

Admin: An account with the organization administrator role associated to a different organization.

Owner: An organization owner account for a different organization.

After clicking the link in the invitation, you can choose the account to use to join the organization.

If the account you want to use is already associated with another organization, an exclamation mark is displayed next to it. This means that additional steps are needed before migrating the account to a new organization.
==== Using an Existing Account

==== Creating a New Account Within an Existing Organization
ou can create a new account within an existing organization only if you receive an email invitation to join the organization.

Click the link in the invitation email.

Click the Sign Up button.
A sign up window is displayed.

Enter the following information in the form:

Full name - First and last name.

Email address - If your email address is associated with more than one Anypoint Platform account, after clicking the link in the invitation choose one of the following:

Using an Existing Account

Creating a New Account Within an Existing Organization

Phone number - Phone number with area code.

Username - You can use the same email address for multiple Anypoint Platform accounts, but each account needs a unique username. This enables you to manage all of your Anypoint Platform accounts under a single email address.
Must be at least 3 characters and contain only the following: alphanumeric characters, dashes, or underscores.

Password - Must be at least 6 characters in length and contain only the following: upper and lower case characters, numbers, and non-alphanumeric symbols.

Agree to the terms of service and privacy policy, then click Accept and create account in <org>.

You cannot create a new account within an existing organization without an email invitation.